### PR TITLE
docs: add North Macedonia and Czech Republic links and apks

### PR DESCRIPTION
**Pull request by Abdelkrim**

### CODE REVIEW

**Comment by fs0c131y** [comment]
Hi,

Thank you for the PR! Before I merge it, can you add cz.covid19cz.erouska and mk.gov.koronavirus.stop to the file packages.txt? Also can you add the APK files in the apks folder?

Regards

**Review by fs0c131y — CHANGES_REQUESTED** [review]
Hi,

Thank you for the PR! Before I merge it, can you add cz.covid19cz.erouska and mk.gov.koronavirus.stop to the file packages.txt? Also can you add the APK files in the apks folder?

Regards

**Comment by Abdelkrim** [comment]
Elliot, I don't know how to download the apks. I'll check tonight
@fs0c131y

**Comment by Abdelkrim** [comment]
@fs0c131y I have uploaded the apk and updated the packages.txt

**Comment by Abdelkrim** [comment]
Hi @fs0c131y , when do you plan to accept the pull requests? :-)

**Review by fs0c131y — APPROVED** [review]

**Comment by fs0c131y** [comment]
Apparently, you have a conflict, can you fix it and I will merge this PR

**Comment by Abdelkrim** [comment]
@fs0c131y voilà, I have corrected the conflict

**Pull request closed without merging**
