### PR TITLE
Add CoronaTrace

### PR DESCRIPTION
**Pull request by dweinstein**
Not yet published on app stores.

### CODE REVIEW

**Comment by fs0c131y** [comment]
Is this app developped by a company or an individual? Should we create a new section? What do you think?

**Comment by fs0c131y** [comment]
Is this app developped by a company or an individual? Should we create a new section? What do you think?

**Comment by fs0c131y** [comment]
Is this app developped by a company or an individual? Should we create a new section? What do you think?

**Comment by dweinstein** [comment]
It is developed by a non-profit organization, see https://www.coronatrace.org/

**Comment by fs0c131y** [comment]
Can you add the corresponding apk to the apk folder and add the package name in the package.txt file?

**Pull request closed without merging**
