### PR TITLE
Merge all four sections into one table

### PR DESCRIPTION
**Pull request by ghost**
This is a follow-up on my comment in issue https://github.com/fs0c131y/covid19-tracker-apps/issues/2#issuecomment-614669202. 

The aim of this PR is to improve the readability of the table and make it ready to add more app projects.

I focused on merging the four tables. I did not do as many changes as I had suggested in https://github.com/fs0c131y/covid19-tracker-apps/issues/2#issuecomment-614669202. I wanted the first issue to focus on the merge, although I did some minor edits and adds. My mistake not to have grouped edits in different commits.

Below are the updates I made:

- I merged all four sections ("governmental", "police", "open source" and "org" apps) into one table because some apps belong to more than one section; e.g.:
  - police apps are also governmental
  - some governmental apps are open source
  - etc
  - suggestion: we could add a "body" column if you want to differentiate between app projects that are developed by ministries of health, eGov agencies, or police forces.
- For each country (when possible) I added the name of the agency or ministry leading the development of the app. I left blank cells for non-governmental apps that aspire to be used cross-borders (i.e. Private Kit). 
- I extended the "website" column to all entries (to be populated.)
- I added an "open source" column. It might be redundant since we have a "repo" column. I am fine with deleting it.
- UK: I updated the name of the UK app to "Zoe Global Limited" since the effort is lead by this private company -- and supported by King's College (need to add the latter.)
- Qatar: I updated the name of the Qatar app to "Droobi Health" since the effort is lead by this private company.
- I deleted the website link (https://www.pepp-pt.org/) of DP-3T; that was incorrect. I added a link to DP-3T's repo (https://github.com/DP-3T)
- I added repositories of some open source projects.
- I added a couple of open source projects: CoEpi, Covid Watch (there is more to be added for a later PR.)

Let me know what you think cc @fs0c131y. I'd be happy to carry on improving the table once we settle on this first PR.

### CODE REVIEW

**Comment by ghost** [comment]
@fs0c131y let me know if you intend to merge it. I will resolve the conflicts.

**Comment by fs0c131y** [comment]
Please, once it's done I will merge it

**Comment by ghost** [comment]
I added Russia (Moscow) as per https://github.com/fs0c131y/covid19-tracker-apps/commit/129b81cea4db051923155979c32c8faf276830b4

**Comment by fs0c131y** [comment]
Thanks for your contribution!

**Pull request merged**
